---

- name: create local quagga folder
  file: path={{quagga_folder_local}} state=directory recurse=yes
  delegate_to: localhost
  become: false
  when: save_local is defined and save_local == "enable"
  tags:
    - quagga_setup
    - local

- name: render zebra configuration locally
  template: src=zebra.conf.j2 dest={{zebra_conf_local}}
  delegate_to: localhost
  become: false
  when: save_local is defined and save_local == "enable"
  tags:
    - quagga_setup
    - local

- name: render zebra configuration
  template: src=zebra.conf.j2 dest={{zebra_conf}} owner=quagga group=quagga mode=0600
  notify:
    - enable zebra
    - check zebra
    - restart zebra
  tags:
    - quagga_setup

- name: render ospfd configuration locally
  template: src=ospfd.conf.j2 dest={{ospfd_conf_local}}
  delegate_to: localhost
  become: false
  when: save_local is defined and save_local == "enable"
  tags:
    - quagga_setup
    - local

- name: render ospfd configuration
  template: src=ospfd.conf.j2 dest={{ospfd_conf}} owner=quagga group=quagga mode=0600
  notify:
    - enable ospfd
    - check ospfd
    - restart ospfd
  tags:
    - quagga_setup
