---
- hosts: localhost
  pre_tasks:
    - name: Verify Ansible version requirements
      assert:
        that: "ansible_version.full is version_compare('2.0', '>=')"
        msg: "Ansible version 2.0 or higher is required to run this playbook"

- hosts: localhost
  user: admin
  tasks:
    - name: include batch vars
      include_vars:
        file: group_vars/batch.yml
        name: batch
    - name: generate all vars for leaf01
      template: src='templates/leaf01_500bgp.j2' dest='host_vars/leaf01_mellanox'
    - name: generate all vars for server01
      template: src='templates/server01_500bgp.j2' dest='host_vars/pprb-1'
