- name: update timezone
  command: tzupdate
  notify: verify timezone

- name: verify timezone
  command: 'date +"%Z %z"'

- name: restart NTP
  service: name=ntpd state=restarted enabled=yes

- name: restart syslog
  service: name=syslogd state=restarted

- name: restart Zabbix Agent
  service: name=zabbix_agentd state=restarted enabled=yes

- name: restart sshd
  service: name=sshd state=restarted

- name: restart LLDP
  service: name=lldpd state=restarted enabled=yes

#Pull the lldp neighbor table
- name: check lldp neighbors
  command: lldpctl
  register: lldpctl_output
  notify: Print lldp neighbors

#Print out the results (Note in the command above you could use JSON output by adding -f json)
- name: print lldp neighbors
  debug: var=lldpctl_output.stdout.split('\n')

- name: restart SNMP
  service: name=snmpd state=restarted enabled=yes
