filters:
    # import_ospf: |
    #     if (source = RTS_OSPF) && (net ~ [ 1.1.1.0/24+, 10.0.0.0/16+ ]) then {
    #             if ( ospf_metric1 < 1000) then {
    #                     accept;
    #             } else reject;
    #     }
    #     else reject;
    # export_ospf: |
    #     if (source = RTS_DEVICE) && ( net ~ [ 1.1.1.0/24+ ] ) then {
    #             ospf_metric1 = 1000;
    #             accept;
    #     }
    #     else reject;
    import_bgp_from_servers_vrf1: |
        if bgp_path.len > 1 then reject;
        if net ~ [ 10.255.1.0/24+, 100.64.0.0/16+ ] then accept;
        reject;

    import_bgp_from_servers_vrf2: |
        if bgp_path.len > 1 then reject;
        if net ~ [ 10.255.2.0/24+, 100.65.0.0/16+ ] then accept;
        reject;

    import_servers_static_vrf1: |
        if net ~ [ 100.64.0.0/16+ ] then accept;
        reject;

    import_servers_static_vrf2: |
        if net ~ [ 100.65.0.0/16+ ] then accept;
        reject;
